import { forwardRef } from 'react'
import type { DiagnosisResult } from '../lib/diagnose'

export const CARD_WIDTH = 1080

type Props = {
  name: string
  result: DiagnosisResult
}

export const ResultCard = forwardRef<HTMLDivElement, Props>(({ name, result }, ref) => {
  return (
    <div
      ref={ref}
      className="bg-gradient-to-br from-slate-50 to-blue-50 p-12 text-ink"
      style={{
        width: `${CARD_WIDTH}px`,
        fontFamily: "'Noto Sans JP', sans-serif",
        wordBreak: 'break-word',
        overflowWrap: 'break-word',
      }}
    >
      {/* ヘッダー */}
      <div className="mb-8 border-b-4 border-accent pb-6">
        <h1 className="text-4xl font-black leading-tight">
          {name}様の<span className="text-accent">才能診断結果</span>
        </h1>
      </div>

      {/* キャッチコピー */}
      <div className="mb-8 rounded-2xl bg-ink px-8 py-6 text-white shadow-lg">
        <div className="text-xs font-medium tracking-widest text-blue-200">
          あなたを一言で表すと
        </div>
        <div className="mt-2 text-3xl font-bold leading-snug">
          「{result.oneLineSummary}」
        </div>
      </div>

      {/* メイングリッド：上段2つ */}
      <div className="mb-5 grid grid-cols-2 gap-5">
        <Section title="やりたいこと" icon="🎯" body={result.yaritaiKoto} />
        <Section title="欲求" icon="🔥" body={result.yokkyu} />
      </div>

      {/* 才能 + 才能方程式 */}
      <div className="mb-5 grid grid-cols-2 gap-5">
        <Section title="才能" icon="✨" body={result.sainou} />
        <Section title="才能方程式" icon="🧬" body={result.sainouHouteishiki} mono />
      </div>

      {/* 発動条件（横長） */}
      <div className="mb-5">
        <Section title="発動条件" icon="⚡" body={result.hatsudouJouken} />
      </div>

      {/* 才能を活かす方法（横長・強調） */}
      <div className="mb-8">
        <Section
          title="才能を活かす方法"
          icon="💡"
          body={result.ikasuHouhou}
          accentBg
        />
      </div>

      {/* フッター */}
      <div className="text-right text-xs text-slate-500">
        Generated by 才能のトリセツ AI
      </div>
    </div>
  )
})

function Section({
  title,
  icon,
  body,
  accent,
  mono,
  accentBg,
}: {
  title: string
  icon: string
  body: string
  accent?: boolean
  mono?: boolean
  accentBg?: boolean
}) {
  return (
    <div
      className={`rounded-2xl border-2 p-6 shadow-sm ${
        accentBg ? 'border-accent bg-accent/5' : 'border-slate-200 bg-white'
      }`}
      style={{ wordBreak: 'break-word', overflowWrap: 'break-word' }}
    >
      <div
        className={`mb-3 flex items-center gap-2 text-sm font-bold ${
          accent ? 'text-accent' : 'text-ink'
        }`}
      >
        <span className="text-xl">{icon}</span>
        <span className="tracking-wider">{title}</span>
      </div>
      <div
        className={`whitespace-pre-wrap leading-relaxed ${
          mono ? 'text-base' : 'text-[15px]'
        }`}
        style={mono ? { fontFamily: '"SF Mono", Menlo, monospace' } : undefined}
      >
        {body}
      </div>
    </div>
  )
}
